version: "3.8"  # optional since v1.27.0
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - SRVC_CONFIG=etc/local.json